 import React from "react"; import "./portfolio.css"; import { Button } from "./components/ui/button"; import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "./components/ui/card"; import { Github, Linkedin, Mail, ExternalLink } from "lucide-react"; import { projects, contact, profile } from "./mock";

function Header() { return ( <header className="header"> <div> <h1 className="header-title">{profile.name}</h1> <p className="header-sub">{profile.tagline}</p> </div> <div className="inline-actions" aria-label="Accesos rápidos a redes"> <Button variant="outline" onClick={() => window.open(contact.github, "_blank", "noopener,noreferrer")}> <Github size={18} style={{ marginRight: 8 }} /> GitHub </Button> <Button variant="outline" onClick={() => window.open(contact.linkedin, "_blank", "noopener,noreferrer")}> <Linkedin size={18} style={{ marginRight: 8 }} /> LinkedIn </Button> </div> </header> ); }

function ProjectsSection() { return ( <section className="section" aria-labelledby="proyectos-title"> <h2 id="proyectos-title" className="section-title">Proyectos</h2> <div className="grid"> {projects.map((p) => ( <Card key={p.id} className="card-override"> <CardHeader> <CardTitle className="card-title">{p.title}</CardTitle> <CardDescription className="card-desc">{p.description}</CardDescription> </CardHeader> <CardContent> {p.isReal ? ( <span className="pill pill-success">Proyecto real</span> ) : ( <span className="pill pill-muted">Placeholder</span> )} </CardContent> <CardFooter> <Button className="accent-button" onClick={() => window.open(p.url, "_blank", "noopener,noreferrer")} > Ver Proyecto <ExternalLink size={16} style={{ marginLeft: 8 }} /> </Button> </CardFooter> </Card> ))} </div> </section> ); }

function ContactSection() { return ( <section className="section" aria-labelledby="contacto-title"> <h2 id="contacto-title" className="section-title">Contacto</h2> <div className="contact"> <div className="inline-actions" style={{ justifyContent: "space-between", flexWrap: "wrap" }}> <div className="inline-actions"> <Mail size={18} /> <a className="link" href={mailto:${contact.email}}>{contact.email}</a> </div> <div className="inline-actions"> <Button variant="outline" onClick={() => window.open(contact.github, "_blank", "noopener,noreferrer")}> <Github size={18} style={{ marginRight: 8 }} /> GitHub </Button> <Button variant="outline" onClick={() => window.open(contact.linkedin, "_blank", "noopener,noreferrer")}> <Linkedin size={18} style={{ marginRight: 8 }} /> LinkedIn </Button> </div> </div> <p className="footer">© {new Date().getFullYear()} {profile.name}. Todos los derechos reservados.</p> </div> </section> ); }

export default function App() { return ( <div className="App"> <main className="container"> <Header /> <ProjectsSection /> <ContactSection /> </main> </div> ); }
